title: Configuration
type: object
properties:
    authkey:
        type: string
        default : verysecretkey
        description: Authkey to read all the text via API
    dayspan:
        type: integer
        default : 90
        minimum: 1
        maximum: 65535
        description: Amount of days the texts stay on the database
    debug:
        type: boolean
        default : false
        description: Enable debug messages
    db:
        type: string
        default: 'pastrami.db'
        description: Path to the database
required:
    - db
additionalProperties: False
