# MIT License

# Copyright (c) 2022, Marco Marzetti <marco@lamehost.it>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

openapi: 3.0.0
servers:
  - url: /api/2.0
info:
  title: Text Copy/Paste Service
  version: '0.2'
paths:
  /:
    post:
      tags:
        - Text
      operationId: pastrami.webapp.post_text
      summary: Post new Text
      requestBody:
        description: Text content
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Text'
      responses:
        '201':
          description: New Text created
  /{text_id}:
    get:
      tags:
        - Text
      operationId: pastrami.webapp.get_text
      summary: Get Text by ID
      parameters:
        - $ref: '#/components/parameters/text_id'
      responses:
        '200':
          description: Return Text
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Text'
components:
  parameters:
    text_id:
      name: text_id
      description: Text's unique identifier
      in: path
      required: true
      schema:
        type: string
        pattern: '^[a-zA-Z0-9-]+$'

  requestBodies:
    text:
      description: Text content
      required: true
      content:
        application/json:
          schema:
            type: string

  schemas:
    Text:
      type: object
      required:
        - text
      properties:
        text_id:
          type: string
          description: Unique identifier
          example: '123'
          readOnly: true
        text:
          type: string
          description: Text snipped
          example: Lorem ipsum
          minLength: 1
          maxLength: 1000000
        modified:
          type: string
          format: date-time
          description: Creation time
          example: '2015-07-07T15:49:51.230+02:00'
          readOnly: true
